services:
  redis:
    image: redis:5.0-alpine3.10
    networks:
      - front
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}  
    volumes:
      - "data-postgres:/var/lib/postgresql/data"
    networks:
      - back
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    #user: "admin:admin"
    depends_on:
      - db
      - redis
    networks:
      - front
      - back
    
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN

    deploy:
      resources: 
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.5"

  vote:
    build: 
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - redis
    networks:
      - front
  result:
    build: 
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "8089:4000"
    depends_on:
      - db
    networks:
      - back

volumes:
  data-postgres:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge