FROM ubuntu:20.04
RUN apt-get update && apt-get install -y nginx
COPY index.php /var/www/html
WORKDIR /var/www/html
EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
ENTRYPOINT ["nginx", "-g", "daemon off;"]