FROM ubuntu:20.04
RUN apt-get update && apt-get install -y nginx
WORKDIR /var/www/html/FOLDER
COPY /FOLDER/. .

EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
ENTRYPOINT ["nginx", "-g", "daemon off;"]
